### ISSUE TITLE
Display the customer info requests in the admin

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#107]
- Read the list of customer info requests
- Display them on the admin page in a table with the following columns:
  - the submission date
  - customer name
  - customer contact email (a click with a mailto link)
  - the status
  - a "view message" button.
  - a "update status" button.

**Comment by damirius** [comment]
@WebDevJL 
I've added new functionalities to the cri admin page. You can now see message by clicking envelope icon in leftmost table cell and it will open up in bootstrap's modal. I've also implemented pagination, which should work nicely together with the filters. I've added new functional tests which also checks pagination links. Also fixed a bug with filtering. Everything is on feature_admin page
You can check out video demonstration here https://drive.google.com/file/d/0B7Laiv0PjSvDQ1FsMVNWbFpMQ1U/view
