### ISSUE TITLE
Activate Bower for CSS and JavaScript packages

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#11]
@damirius @gsouvik 
Have you used Bower (http://bower.io) before? I'd like to use a good solution to compress css and js in order to limit HTTP requests on page load.

Thanks for sharing!

**Comment by damirius** [comment]
@WebDevJL 

I use bower often, but bower is essentially packet manager just like composer.
If we are talking about combining js files to limit number of requests per page, check out assetic bundle http://symfony.com/doc/current/cookbook/assetic/asset_management.html
It can combine multiple javascripts in one file and serve it like that.

**Comment by WebDevJL** [comment]
@damirius Thanks for the answer. I'll add a new task: "Enable CSS and JS bundling".

**Comment by WebDevJL** [comment]
@damirius Let's use bower to manage the following packages :
- twitter bootstrap 
- jquery 

We will add other packages as we go.

**Comment by WebDevJL** [comment]
@damirius This is to do last in your task list.

**Comment by WebDevJL** [comment]
@damirius if you are wondering what I ran to have the error in commit c03eeb1, check the script sh/install.sh on the optimisations branch

**Comment by WebDevJL** [comment]
**_Note:**_ MUST install node.js to work with bower. See Damir's comment in c03eeb1
