### ISSUE TITLE
Add version number to css and js bundled files

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#118]
@damirius 

Is that possible? If so, please do it so it is just about changing one value as a parameter. 

This will force a refresh of the css on client's browser.

**Comment by damirius** [comment]
@WebDevJL 
Something like this http://symfony.com/doc/current/reference/configuration/framework.html#reference-framework-assets-version?

**Comment by WebDevJL** [comment]
@damirius Spot on! Go for it :+1:

**Comment by damirius** [comment]
@WebDevJL 

It's on feature_appoptimisation branch. I've just added 'release_version' under params in config which we can reuse for other stuff if needed also. Keep in mind that cache busting with version for bundled css/js files is done only in production not in dev mode. In dev mode that's already done by dynamically fetching of assets, also they aren't bundled up there for easier debugging.
