### ISSUE TITLE
Enable email sending and translations for new CRIs

### ISSUE THREAD

**Issue by damirius** [Puzzlout/TrekToursFlyer#153]
Add email templates and translations on the application side instead on API
see https://github.com/Puzzlout/TrekToursApi/issues/24

**Comment by damirius** [comment]
@WebDevJL 

Since both emails are sent from 'noreply@domain.com', I think that we should also include email and phone number (if set) in email template that is sent to the admin. Since from that notification they will only see the name, of course they can login to the apps admin panel to check everything that was sent through the form.

For now admin template is looking like this:

```
Hello,

You received a message from {{ name of customer }}:

{{ customer message }}
```

We can change it to something like this

```
Hello,

You received a message from {{ name of customer }}:

{{ customer message }}

Email: {{ email }}
Phone number: {{ phone number }}
```

We can keep the client copy like this:

```
Hello {{ name of customer }},

You have sent the following message:

{{ customer message }}
```

**Comment by WebDevJL** [comment]
@damirius yes of course it makes sense to include phone number and email
address.

## 

Jérémie Litzler

**Comment by damirius** [comment]
@WebDevJL 

New stuff is on feature_contact branch.

**Comment by WebDevJL** [comment]
@damirius I cannot see if the emails were really sent. Do we have the tests to validate email sending? From what I see in the database, it seems so since the dates we added are set.

Also, we would gain in clarity if we put the code in BusinessLogic classes under the AppBundle, like "AppBundler > BL > Contact > FormSubmissionHandler class" and "AppBundle > BL > Emailer class".
In fact, I'd like to keep methods under 25 lines long.

Can you do that and figure out why the email sending seems not to work? If the email server is failing, let me know because my hosting provider didn't any connections... 

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I want to test it out on my c9 workspace, but for some reason c9 is down. I have some problems on local with opening up smtp connections, don't know if my router is the problem or some firewalls (i turned them off of course) or some php settings, so I want to test it live, since I know this one is problem with the local setup.
Also I found that email spooling was on by default and in that case `send` function always returned 1 which caused script to update `sent` dates over API. With email spooling emails aren't sent until later so that client doesn't have to wait for email transfer to finish. I turned off email spooling which will cause that particular controller action to slowdown a bit, but not much since we aren't sending any attachments, just html and text emails. In our case where we want to immediately check if email is sent we can't have it on.
I now want to see if rest of the changes I made to the config will actually send the email where there isn't any problem with the actual server, so I'll have to wait till my workspace comes back again.
Sorry for not responding earlier, I got a light fever, I'm little better now than I was over the weekend so I don't think I'll be out for next few days.

Thanks

**Comment by WebDevJL** [comment]
@damirius I hope you will get better soon. And no worries about  not
responding sooner. I am not expecting a 24/7 direct line to you ;)

So about our task: yes C9 login is down... Stéphane asked me the same. The
platform looks feverish too. In the meantime, can you work on the admin
navbar?

And yes, ok for spooling off since emails are small.

Thanks for the details again

**Comment by damirius** [comment]
@WebDevJL 

Thanks.

I'll work on navbar, not a problem.

**Comment by damirius** [comment]
@WebDevJL 

I played around with mailer settings, tried to use 'ssl', 'tls' and different modes of password encryption, but to no avail. On c9 I get connection timeout. I also downloaded mail client so I can test from there and I can't get it working. Can you tell me if password is OK and exact settings for your mail server? Just want to double check everything since I can't make it work with it.

**Comment by WebDevJL** [comment]
@damirius 

I reset the password:
![image](https://cloud.githubusercontent.com/assets/3506074/16949175/89e26710-4db9-11e6-8082-abd5aeb82556.png)

And here are the mail server details:
![image](https://cloud.githubusercontent.com/assets/3506074/16949190/9f353c82-4db9-11e6-8e9b-df24b53fc52e.png)

Let me know if you achieve something with that.

**Comment by damirius** [comment]
@WebDevJL 

Can you send me the email with that info? It seems I can't configure my thunderbird to work with those params, maybe I'm not entering correct password because of those Is and Ls. I want to see if they are maybe filtering IPs or something like that so we can't make connection

**Comment by WebDevJL** [comment]
email address: noreply@puzzlout.com
email password: noreply%trektours%16
smtp / pop3 server: mail.supremecluster.com

On my hosting provider, nothing is blocking anyone (yet).

**Comment by damirius** [comment]
@WebDevJL 

It seems I can't set it up on thunderbird. I tried setting up POP3, on default port for pop3 with plain password I get invalid password, no other password encryptions are supported. For SMTP on port 25 connection can't be established at all, I can only use SSL on port 465. This one establish connection for both plain and encrypted password auth modes, but in both cases it still tells me that password isn't correct.

**Comment by WebDevJL** [comment]
@damirius I got working on GMAIL...

![image](https://cloud.githubusercontent.com/assets/3506074/16952923/88885c5a-4dcb-11e6-887b-6cb1adab3de8.png)

If you can't make it work, create a gmail account "noreply.trektours@gmail.com" with same password and try that.

**Comment by damirius** [comment]
@WebDevJL 

Finally! I managed to setup both gmail and thunderbird for sending emails so everything is OK with your account. Unfortunately, after a long time, I found out that c9 is blocking smtp ports to prevent spam sending from their servers... Luckily I managed to set it up on local machine to work with mailcluster!
It took some time, but it's set now. We can also use gmail instead of smtp (I think in that case it automatically sets up host and everything else). I've tested that case first with my gmail account. So we can always go for that too

**Comment by WebDevJL** [comment]
@damirius I see the password is still the old one... does it really work?

**Comment by damirius** [comment]
@WebDevJL 

That's just dist version, when you run composer update or install you should just enter new password if you wish. 
Since dist version isn't used for anything except for installs/updates, real params should be stated in `parameters.yml` not in `parameters.yml.dist`
I'll see that I send you some test mail from my local machine.

**Comment by damirius** [comment]
@WebDevJL 

You should get couple of emails

**Comment by WebDevJL** [comment]
@damirius I got the test emails :) I will try on c9 but can you share the
procedure to open smtp ports on c9 for install from scratch? Also tell me
how long it took you to do all this troubleshooting because we could go
faster if we had a real hosting service and this scenario is a good
argument to speed up the booking process.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I don't believe there is some specific procedure to open up smtp ports on c9. I mean you could probably ask their support, but they don't want to let people enable smtp because of that spamming problem.
Well most of the day I was looking around c9 trying to get it right and some time before c9 had that problems with their workstations. So yea lost some time on that, plus I had problems with local setup too so that's just a plus.

**Comment by WebDevJL** [comment]
@damirius Ok it works locally but it is impossible to make it work on C9.
Thanks for your investigation. I guess we will test the real email sending
later. I will create tasks so we don't forget.
