### ISSUE TITLE
Add quick link in admin area to view CRIs

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#155]
@damirius just after the login, we need a quick link for CRIs just like the translation panel.

**Comment by damirius** [comment]
@WebDevJL 

It's on feature admin branch.
We should maybe implement some navbar on all admin pages for easier navigation.
Don't know where we are on design side of things, so I don't want to change anything now.

**Comment by WebDevJL** [comment]
@damirius yes go for the navbar. The design job is only the public side.
The admin area is not critical.
Open up a time new issue for that.

We have not picked a designer yet but we have leads. It is difficult to
find the right fit. Maybe next week.

## Thanks for asking.

Jérémie Litzler
