### ISSUE TITLE
Create shared view for navigation menu

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#16]
The Navigation menu will be made of the following link for the flyer:
- Home
- Products (a list of 2 items or treks)
- Contact

Make it always visible as the user scrolls down. 
The background color should be in contrast with the content behind.

**Comment by damirius** [comment]
@WebDevJL 

I've added dropdown submenu in navigation, and added scroll effect, so when user scrolls navbar is getting more opaque until it becomes 100% white. We can change colors of the background, but we must agree on general theme of the website, check issue #13 if you can.

Thanks

**Comment by WebDevJL** [comment]
@damirius Use the same theming as the black background and white text of the design for now.

**Comment by damirius** [comment]
@WebDevJL 

This commit also takes care of #47 together with last few commits regarding the footer and language menu
