### ISSUE TITLE
reCaptcha: implementation on contact page

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#166]

**Comment by damirius** [comment]
@WebDevJL 

It's on this week's sprint branch. I reworked form templating and implemented 2 step verification on the client side. Secret and key are stored in params and they should be copied over on install/update. Remember that we need to whitelist every domain that's using this captcha. "c9users.io" domain should be whitelisted and this includes all subdomains, so I think testing on workspaces will work too. Of course we should create new reCaptcha account for production release.

**Comment by damirius** [comment]
@WebDevJL 

**reCaptcha install step by step**
1. Go to https://www.google.com/recaptcha/intro/index.html and clock on "Get reCaptcha" button (you must have registered google account)
2. Register new reCaptcha by filling up "label" and "domains" fields. "labels" is just a name you want to give to this instance of reCaptcha, but "domains" should be valid domains field on which you want to use reCaptcha verification add "127.0.0.1" for local
3. On creation of our project either through "composer install" or "composer update" or by calling "install/update" scripts you will be prompted to enter missing parameters for `parameters.yml` file. One is called `recaptcha_secret` and other is `recaptcha_key`, `secret` is used on the server side, and like it's name tells us, it should be kept secret. `key` is public and when we want to initialize it through the script tag in our templates we gonna use that key.

****Note**** that in `parameters.yml.dist` are the default secret and key for the reCaptcha, just like for everything else and you can keep them for the testing, those are key and secret setup for my test reCaptcha instance which we can use for all kinds of testing. So for now there's **no need** to register new reCaptcha, just add those existing parameters in parameters.yml file and that's it
These are whitelisted domains:

```
localhost
trektoursflyer.dev
c9users.io
127.0.0.1
```

**Comment by WebDevJL** [comment]
@damirius Thanks Damir.

**Comment by WebDevJL** [comment]
@damirius 2 questions for you:
1. what account do you use for the reCaptcha setup?
2. can you setup the reCaptcha on this account: trektours.apps@gmail.com. I will send you the password.
3. can you add the puzzlout.com domain to the whitelist? 

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I use my gmail account for testing.
I can set it up on that mail and add everything to the whitelist that's needed. We can keep using that gmail for other stuff that we will need later on, analytics, web master tools and other gmail services like apis and such if you like

**Comment by WebDevJL** [comment]
@damirius Yes indeed. Analytics will be setup with this account.

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by damirius** [comment]
@WebDevJL 

Changed reCaptcha keys in dist parameters on sprint branch

**Comment by WebDevJL** [comment]
@damirius I will wait for your release 1.0.2-RC1 on the VS deploy folder to test this. Thanks.

**Comment by WebDevJL** [comment]
@damirius this is working but where does the label "reCaptcha error" comes from? I don't find it in the translation set...
