### ISSUE TITLE
UX work of the main layout

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#180]
Please submit comments and work here. use @webdevjl to notify me. Thanks.

**Comment by WebDevJL** [comment]
![ebikemontblanc](https://cloud.githubusercontent.com/assets/3506074/18337184/903efc02-758e-11e6-847b-f7eee775ffee.jpg)
- [x] is it possible to have a version in a few color themes?
- [x] what about the mockup in tablet and smartphone format?
- [x] name of logo needs a different color so that ebike standouts more
- [x] modify the text color so that it is more visible over the background image
- [x] modify the background image of the contact bloc or use an icon (look at fontawesome: http://fontawesome.io/)

**Comment by WebDevJL** [comment]
This is the final design chosen:

Desktop:
![ebikemontblanc](https://cloud.githubusercontent.com/assets/3506074/18415908/176e260a-7803-11e6-968f-0e8e09524912.jpg)

Smartphone:
![ebikemontblanc-smartphone](https://cloud.githubusercontent.com/assets/3506074/18415914/3fa57056-7803-11e6-92a6-0277d7eda4f3.jpg)

For tablet, we need to find the breaking point for the button "Learn more" in the top section.

**Comment by nchapelain** [comment]
[Archive 3.zip](https://github.com/Puzzlout/TrekToursFlyer/files/471458/Archive.3.zip)
Voici la version intégrée pour validation.

**Comment by WebDevJL** [comment]
@nchapelain 

Voici mes retours:
- [x] il faut limiter la largeur minimum à 320px. 
- [x] sur le top menu, entre la largeur 993px et 789px, les éléments du menu passent sous le nom "ebikemontblanc". Il faudrait réduire la taille de police du nom comme fait à partir de 788px et en-dessous.
- [x] comme vu ensemble, on n'aura qu'un trek à proposer donc merci de ne pas mettre le menu déroulant sur "eBike Mont-Blanc Treck". il faut juste avoir un lien comme cela est fait pour le lien "Accueil" et "Contact".
- [x] le bouton "Learn More" ne doit pas venir se superposer sur les personne de l'image du premier bloc.  Merci de le mettre sous l'image lorsque ce bouton en dessous de 360px de large.
- [x] ne pas inclure l'HTML du carousel car nous ne l'utilisons pas.

**Comment by nchapelain** [comment]
[Archive 4.zip](https://github.com/Puzzlout/TrekToursFlyer/files/471706/Archive.4.zip)
voici les modifications
Concernant le cta du header, je pense qu'il est préférable de le laisser sur l'image, je l'ai donc descendu (en 360px) juste en dessous du coude du personnage de gauche, mais si tu préfères je le met sous l'image (comme indiqué). Ce n'est qu'une proposition de ma part.
Nicolas

**Comment by WebDevJL** [comment]
@nchapelain 

Un dernier point :
- [ ] le nom "ebikemontblanc" n'est pas aligné au centre entre les largeurs 768px et 996px. Serait-il de l'aligner dans la bar de menu ?

Après cela, je vais montrer ça à Stéphane. Merci.

**Comment by WebDevJL** [comment]
@nchapelain 

Stéphane a fait une remarque :
- [ ] peut-on avoir l'image du premier bloc en mode "plein écran" peu importe la largeur du viewport ?

**Comment by nchapelain** [comment]
tu veux dire, sur toute la hauteur ?

**Comment by WebDevJL** [comment]
@nchapelain 

Oui, la hauteur du bloc "hero banner" devrait être 100% du viewport du terminal. Pour le moment, ce n'est pas le cas :

![image](https://cloud.githubusercontent.com/assets/3506074/18511426/eaca7382-7a83-11e6-90fc-d1a68e11f2c9.png)

**Comment by nchapelain** [comment]
Je peux mettre l'image en hauteur 100% mais cela veut dire que si l'écran est plus large que haut il y aura des bordures a gauche et a droite... c'est une question de proportionalité !!

**Comment by nchapelain** [comment]
actuellement le css de l'image est en "cover", on peut le changer sans aucun soucis

**Comment by WebDevJL** [comment]
@nchapelain 

Le but est d'obtenir ceci: http://blackrockdigital.github.io/startbootstrap-full-slider/ (sans le slider, juste la partie "image full viewport"). Est-ce assez précis ?

**Comment by nchapelain** [comment]
c'est en effet beaucoup plus précis, alors voici
[Archive 6.zip](https://github.com/Puzzlout/TrekToursFlyer/files/472007/Archive.6.zip)
