### ISSUE TITLE
Impossible to send a CRI on QAS flyer

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#186]
@damirius 

QAS flyer: http://puzzlout.com/trektours/public/web

The submission of a CRI doesn't seem to work... Can you look at it?
![screen shot 2016-08-07 at 12 42 49](https://cloud.githubusercontent.com/assets/3506074/17461960/d2848e16-5c9c-11e6-80b4-8eef96383c53.png)

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I'll check with support if smtp is blocked or something like that

**Comment by damirius** [comment]
@WebDevJL 

Yap, it was blocked in the firewall. Support guy was more than helpful so we solved it in a reasonable time. I'll add this in coming week sprint, but it bugged me so I wanted to solve it asap.

Tested it on all 3 apps, if I'm not mistaken you should probably get some test mails on 'contact@puzzlout.com'
