### ISSUE TITLE
SSL mail issue with LiquidWeb

### ISSUE THREAD

**Issue by damirius** [Puzzlout/TrekToursFlyer#190]

**Comment by WebDevJL** [comment]
For the record:

> @damirius's analysis and solution:
> I was talking with support staff of LW for more than a week, I talked with at least 5 different guys ☺ They claim that it's the problem with SSL connection and that we should use TLS
> Since SSLv3 is unsecure and most servers switched to tls1/tls1.1/tls1.2
> that's correct but I still don't think that's the main reason why it didn't work
> SSL worked OK and it just stopped working something like 10 days ago when we tried to test it. They claim that mail.supremecluster.com server stopped supporting sslv3, but I can still connect over ssl from my local machine. In any case I opened 2525 port on LW and connected that way and then started TLS connection with startTLS command
> which is a nice solution I think, we still use secure connection, we still authenticate using cram-md5 and everything should be working and it also works on my local machine
