### ISSUE TITLE
On/Off switch for Bower

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#195]
@damirius 

Here is a task to be able to remove the dependency on root access on the server.
If I am not mistaken, when I look at the project, we only need root access for Bower install of the Flyer application.

Can you confirm that install the Symphony API and Flyer apps don't require root access?

If you answer yes to the above question, can you add a switch to be able to use or not use bower when installing the application? 
Of course, this includes to download add to the project the CSS and JS framework used.

The reason is that the client is wondering if we can install the API and Flyer on a 12€/month hosting service instead of the 5 times more expensive LiquidWeb VPS. 
The VPS will be useful in the future or if the client decides to keep paying LiquidWeb VPS fee. For now, we need to be able to test Symphony apps install on regular shared hosting.

Let me know if you have questions.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

If that's shared hosting how does it have shell access at all?
Also I've mentioned linode before but here it is again https://www.linode.com/pricing
I'm using that first plan for quite a while now and it's 10$ per month.

**Comment by WebDevJL** [comment]
@damirius

Yes, I have a hosting service with HurrayHost that has shell access.
However, it is expiring on Sep 15th and I don't know if I will renew.

Let me know what you can do before then.

Thanks.

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by WebDevJL** [comment]
@damirius Don't work on this for now. I have to give Stéphane a feedback about what can be done.

Thanks.
