### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#196]
@damirius 
1. create a UA code for the codereview and trektours deployed applications using the GMAIL used for reCaptcha
2. add it to the flyer website as a new parameter.
3. make sure that when the user clicks "I don't want to give my consent" that all traffic is tracked by GA.

Let me know if you have questions.

**Comment by damirius** [comment]
@WebDevJL 

Commit should be on new sprint branch.
I've added new param which should be set on install, you can find tracking codes on google analytics page when you log in with trektours app google account. I've setup two different tracking codes one is called flyer codereview other is flyer deployed. We can change the names if needed and other settings or even add new ones if you wish.
Analytics code is in it's own module and it will be added to each App page on flyer, so everything in the frontend. Admin panel isn't tracked. Also analytics will not be included unless user presses Agree on our cookie agreement bar. 
I've also tested that with functional tests, when client cookie is set to 1,0 or unset.

**Comment by damirius** [comment]
@WebDevJL 

I've also added new travis custom code for testing, since travis was showing some errors because of it. We can also use it when working or we can use some other. Note that if I'm not mistaken analytics code will work only if called from the registered domain. For now registered domain is puzzlout.com. We can change it later or add new codes for different domains

**Comment by WebDevJL** [comment]
@damirius Great. We will look at this during next week release.

Later, we will need to add the domain "ebikeouting.com" and add a new code.
I need to confirm the DNS A Record to add the domain to LiquidWeb serveur.

Thanks for the work.

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com
