### ISSUE TITLE
Contributor permissions working?

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#2]
@gsouvik @damirius,

Please confirm you have permissions to push, pull and clone the repository.

Thanks.

**Comment by WebDevJL** [comment]
@damirius 

i have modify the Puzzlout organisation default permissions on the repos. You should be able to push now.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I can push, just did it with gitignore on master branch. So I'm good
