### ISSUE TITLE
Translation Lexik Bundle preview

### ISSUE THREAD

**Issue by damirius** [Puzzlout/TrekToursFlyer#20]
@WebDevJL 

I had to open this issue on this repo, so I can push my branch on it.
I'll do that now and I'll write explanation how to install it.

**Comment by damirius** [comment]
@WebDevJL 

New commit on feature_translations branch, fetch it and run `composer update` to install it.
Everything should be configured, so after you install it through the composer just run `php bin/console doctrine:schema:update --dump-sql` to see which queries should be executed, new tables should be created automatically. After you double check that you can run `php bin/console doctrine:schema:update --force` to actually run the queries.
After that just in case run `php bin/console asset:install` to install lexik bundle assets in the web directory.
If you open up _app/config/routing.yml_ you will see new entry for lexik stuff with prefix translation.
Just open up http://localtrekdomain.dev/translation/ to see the overview and control panel for translation management.
I've implemented through the twig some demo translations, so you can open up http://localtrekdomain.dev/product/1 to see the product page with translations. Since I didn't want to take much time for this demo, you can change locale by typing locale after the product id, like this http://localtrekdomain.dev/product/1/en where en is locale, so if you want fr locale just open up http://localtrekdomain.dev/product/1/fr

**Comment by WebDevJL** [comment]
@damirius That looks nicely from your description. Can't wait to test it.

**Comment by damirius** [comment]
@WebDevJL 

Forgot to tell you one thing about it, if you noticed in my video lexik bundle is automatically caching everything so that it doesn't look everytime in the db for translations and it's creating some cache files. When you add or modify translations be sure to press "clear cache" button in translation management panel so that you refresh the translations.

**Comment by WebDevJL** [comment]
@damirius 
I did the following:
- modified the database details to make the first commands work locally for me.
- ran `php bin/console doctrine:schema:update` without `--sql-dump`because I had a :

```
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--sql-dump" option does not exist.    
```
- ran `php bin/console doctrine:schema:update --force`
- and finally ran `php bin/console asset:install`

Now, I have questions:
- http://trektoursflyer.dev/translation/ gives me a 404. Why? I can view this page fine: http://trektoursflyer.dev/product/1
- http://trektoursflyer.dev/product/1/en or http://trektoursflyer.dev/product/1/fr gives me a 404 as well. Why?

Thank you for helping out.

**Comment by damirius** [comment]
@WebDevJL 
It's `--dump-sql` not `--sql-dump`, my bad. It's just a command to show you all sql queries which will be executed on `--force`.
Double check ProductController, is there $locale parameter in getAction method? Just want to double check that if everything is pulled on feature_translations branch.
If it is, can you tell me how did you fix that issue you had with feature_product_page branch where you couldn't see view page properly?
Maybe it's problem with cache again, you can always try to run `php bin/console cache:clear --env=prod` or `php bin/console cache:clear --env=dev` depending on which environment you are running your app.

**Comment by WebDevJL** [comment]
@damirius I will try that as soon as I am back home in front of my computer. In fact, it may just be `php bin/console cache:clear --env=dev` that I need. 

However, I thought in dev, caching was built at every request?

If not, maybe, we could have a a set of .sh scripts that helps us with these issues.

**Comment by damirius** [comment]
@WebDevJL 

With dev it should rebuild stuff on calls, so yea don't know if it's because of cache, but it doesn't hurt to try with simplest solutions :)

**Comment by WebDevJL** [comment]
@damirius 

I have removed my local clone and reinstalled it with the following steps:
- ran `composer install`
- ran `composer update`
- created the database symfony with UTF8 unicode encoding in MySQL workbrench
- ran `php bin/console doctrine:schema:update --dump-sql`
- ran `php bin/console doctrine:schema:update --force`
- ran `php bin/console asset:install`
- went on http://trektoursflyer.dev/product/1/en and http://trektoursflyer.dev/product/1/fr but didn't see any differences.
- went on http://trektoursflyer.dev/translation but no items where available. 

So my questions are:
- how do you add a translation via the translation interface?
- why is your example not showing in my clone? Am I missing a step? Are you running commands that are absolutely necessary?

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

The idea of Lexik Translation bundle is to setup default translations like you would for AppBundle domains. So we need to create _domain.en.yml_ files under `Resources/translations` in our AppBundle and populate it with default values.
After that we can import those values from the translation files to the DB tables for Lexik:
`php bin/console lexik:translations:import AppBundle --cache-clear`
When you go to http://trektoursflyer.dev/translation/grid page you should see all existing translations for imported domains and you can edit them. That's it, just clear the translation cache by clicking the 'clear cache' button on that page when you are done and everything should be translated.

**Comment by WebDevJL** [comment]
@damirius Got it working! And I think I understand how it is working. I may play with it later. Thanks.

**Comment by WebDevJL** [comment]
Just a summary of translation commands installation:

```
composer update
php bin/console doctrine:schema:update --dump-sql
php bin/console doctrine:schema:update --force
php bin/console asset:install

```

Finally, load the translations into the database: `php bin/console lexik:translations:import AppBundle --cache-clear`

Url is:  http://trektoursflyer.dev/translation/grid
Click the button "Clear cache" after editing translations.
