### ISSUE TITLE
What are the requirements to add HTTPS on Flyer?

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#218]

**Comment by damirius** [comment]
@WebDevJL 

I think we can setup everything through cpanel. Just go to cpanel for our new domain. Under Security tab we have SSL/TLS page. Click on it and you will see "Certificate Signing Request", we will need to make on of these if we want to purchase some certificate from trusted sellers. Now only important thing is that there are multiple kinds of SSL certificates, there is wildcard which cover domain and all it's subdomains, there is multiple domain cert and of course there is single domain cert.

**Comment by WebDevJL** [comment]
@damirius

Ok. I think Stéphane will purchase the certificate on OVH.
Can we add any (external to LiquidWeb) SSL certs in the interface?

We may need to specify to him that the domains "ebikemontblanc.com" and
maybe "api.ebikemontblanc.com" must be included in the certificate.

We will see.

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by damirius** [comment]
@WebDevJL 

We will have to make that Certificate Signing request before ordering, SSL cert providers will often ask for it so they can verify the domain. Single domain certificates cover only master domain so if we want api subdomain too we could probably buy one more cert or buy wildcard one (it is of course more expensive).

**Comment by WebDevJL** [comment]
@damirius see #216. It is easier than expected.
