### ISSUE TITLE
Fill out all the labels for Home page

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#219]

**Comment by over-e** [comment]
Jeremie

A partir de quel URL je peux saisir les labels  
http://puzzlout.com/trektours/public/web/admin/login  ?

**Comment by WebDevJL** [comment]
@over-e: Je mettrai le guide utilisateur à jour. Pour le moment l'url est
http://ebikemontblanc.com/admin

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com
