### ISSUE TITLE
Building an API

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#22]
@damirius @gsouvik 

I want us to start brainstorming about the API we will build for the project.
We will have, on the long term and not limited to, the following items (list to be extended as we progress):
- A storefront of products
- The storefront will have functionalities to:
  - make orders
  - create user accounts
  - submit product reviews
- A backend website to administrate the storefront including:
  - Monitoring orders
  - Monitoring reviews
  - Managing translations
  - Managing customers
  - Managing products

Now, the first question I ask myself: Can all the above be done in an API to manage all the business logic? Several REST services could allow to request data from that API to then display the retrieved data to the storefront and backend website.

What questions and comments do you have about that possible solution? It would mean that the flyer website we are working on here will use the REST services and the API will be a separate repository.

Thanks for your help on this.

**Comment by gsouvik** [comment]
@WebDevJL 
Using an API for all data interchange is a good idea.
I have a question related to your last couple of the lines of the message. Do you mean to say that the flyer website will "use" data from that API and the API in itself will be a different project with separate repository?

**Comment by WebDevJL** [comment]
@gsouvik @damirius 

Yes, the flyer and later the storefront will request the data from the API.
Yes, the API could be a separate repository because it would separate the business from the presentation.

Make sense?

**Comment by gsouvik** [comment]
@WebDevJL 
Sounds good to me, so we will need to have an authentication layer wrapping the API server as well which will grant access to our consumers and restrict anonymous calls, sort of oauth.

**Comment by damirius** [comment]
@WebDevJL

We gonna continue working with flyer website like we started or you want to make the split now onto API and front?

**Comment by WebDevJL** [comment]
@gsouvik why not.
@damirius no, for now, we keep working like we do because budget is low. This is just brainstorming. So what do you think? :)

**Comment by damirius** [comment]
@WebDevJL 
Well like I said in one of the emails, I'm mostly working like that. Create an API with Symfony usually and then later worry about front end stuff which will use that API. It's great that you can have multiple apps communicating with the same API and it can be rather extendable. You can easily create some mobile app or desktop app or whatever you need later on.
For authentication, well it depends on what we want. I've used JWT authentication, it's light and it works. I guess OAuth would be better if we need to have 3rd party apps.

**Comment by WebDevJL** [comment]
@damirius @gsouvik 

Yes, all that is one more reason that we will go that direction.

Regarding authentication, does not OAuth require a server setup to work? It would indeed by very useful because we might integrate FB, G+ and other third party SSO in the customer account creation.

Does any of you have experience OAuth? 
Can we do JWT as first option and add OAuth as second option once third parties SSO are a go?
