### ISSUE TITLE
Milestone B - Home page

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#223]
See [Milestone B description](https://docs.google.com/document/d/1diPMbzZgxN8ndFfOn1uT3oIk0UzK5W6et9hik-0FGNk/edit#heading=h.z85fnsmm5n0g).

**Comment by WebDevJL** [comment]
@nchapelain please commit the next updates into the folder ["design"](https://github.com/Puzzlout/TrekToursFlyer/tree/s-36-37-16/design) as described below.
- [Install Git](https://git-scm.com/download/mac)

Then just run the following commands on your local Macintosh with the Terminal app:
- run `git clone https://github.com/Puzzlout/TrekToursFlyer.git` anywhere on your Mac
- Modify the files in the TrekToursFlyer/design folder to solve the points listed in the [review document](https://docs.google.com/document/d/1UjX6t7O20R4qSsmCruJH16e1MIZ20ncfqX4COaS2VXE).
- then run 
  - `git add -A`
  - `git commit -m "#223" -m "Updates to the static design"`
  - `git push`
  - enter your GitHub credentials when asked.

**Comment by WebDevJL** [comment]
@damirius you can continue integration after completing #177

**Comment by damirius** [comment]
@WebDevJL 

Pushed on branch

**Comment by WebDevJL** [comment]
@damirius after a quick initial review, it looks like you managed to do a good job. More soon. Thanks.
