### ISSUE TITLE
Create controller to manage common modules

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#23]
We need a controller to manage all common modules:
- header menu
- language menu
- footer section
- partner section
- socail media section
- cookie consent banner

**Comment by damirius** [comment]
@WebDevJL 

I created simple partial view controller with empty twig views which will use to split them up from general layout

**Comment by WebDevJL** [comment]
@damirius I will wait you complete #13, #25 and #26 to check this issue and #16. Let me know when you are done.

**Comment by WebDevJL** [comment]
@damirius actually, it is fine as it is. I will move this to Release.

Thanks!
