### ISSUE TITLE
Message acceptation cookies

### ISSUE THREAD

**Issue by over-e** [Puzzlout/TrekToursFlyer#237]
sur PC et Android 

Le message acceptation cookies apparait sur chaque page , l'action d'acceptation ou refus ne change rien.
Si on retourne sur le site après avoir accepté, le message réapparait

**Comment by WebDevJL** [comment]
@over-e 

Quelle navigateur sur PC ?
Quelle version d'Android ?

Merci.

**Comment by over-e** [comment]
Dans les parametres de firefox, j'ai mis "cookies autorisés" au lieu de "cookies interdit" et maintenant plus de problème

Sujet clos
Merci
