### ISSUE TITLE
formulaire de contact

### ISSUE THREAD

**Issue by over-e** [Puzzlout/TrekToursFlyer#238]
- Dans la page formulaire de contact : décaler le texte "m'envoyer une copie" vers la droite et remettre l'ensemble un peu plus à gauche

- mettre le Captcha plus sur la droite de la page (pour être "équilibré" avec "m'envoyer une copie) 

- mettre le texte "nom" "prénom" etc... en plus gros

**Comment by WebDevJL** [comment]
@over-e que dis-tu de ça ?
![screen shot 2016-11-28 at 06 40 16](https://cloud.githubusercontent.com/assets/3506074/20657370/98d411fe-b535-11e6-827b-50be875ccc71.png)

**Comment by over-e** [comment]
Il faudra plus décaler le texte

![image](https://cloud.githubusercontent.com/assets/19967972/20794297/e02d8eac-b7cb-11e6-826a-fe3adf915a73.png)

**Comment by WebDevJL** [comment]
@over-e peux-tu me préciser de combien  en faisant une copie d'écran
complète de la page et en indiquant la direction ?

Merci.

**Comment by WebDevJL** [comment]
@over-e  peut-on fermer ce bug?
