### ISSUE TITLE
Taille des polices sur page "Produit"

### ISSUE THREAD

**Issue by over-e** [Puzzlout/TrekToursFlyer#240]
Dans la partie ou l'on met les difficultés , durées ........

Il faut mettre le texte _durée_ "6 nuitées" et   _période_ " de juin à septembre" en plus grand

**Comment by WebDevJL** [comment]
@over-e j'ai unifié l'html pour suivre une meilleur hiérarchie (h1 > h2 > h3 > p). Cela donne du texte plus adapté à chaque contexte. La taille de police sont celles de Bootstrap qui optimise la taille en fonction du terminal.
