### ISSUE TITLE
Page produit : Barre de navigation

### ISSUE THREAD

**Issue by over-e** [Puzzlout/TrekToursFlyer#241]
Un des plus qui justifiait de faire des développements tait la barre de navigation de la page produit

Il faudrait la remettre car elle personnalise très bien le site et le rend unique.
pour la partie smartphone, même si elle n'est pas super ergonomique, elle est intéressante.

A discuter ensemble ....

**Comment by over-e** [comment]
J'ai remarqué que le Captcha est toujours en Français, p, tu me confirme que cela dépend de la langue du navigateur 

Si oui alors on peut fermer le point

**Comment by WebDevJL** [comment]
@over-e Tout à fait. Cf ci-dessous:
![recaptcha1](https://cloud.githubusercontent.com/assets/3506074/20874686/8548353c-bab4-11e6-823d-e41268e789f3.png)
![recaptcha2](https://cloud.githubusercontent.com/assets/3506074/20874687/854d0576-bab4-11e6-93f8-69db8dd99ece.png)
