### ISSUE TITLE
Site Admin : Grid translation - saisie de caractères "espace"

### ISSUE THREAD

**Issue by over-e** [Puzzlout/TrekToursFlyer#245]
Site Admin : Grid translation : Lorsque l'on saisi des "espaces " dans un texte , ils sont supprimés lors de l'enregistrement.
Mettre des "espace" est indispensable pour permettre d'aligner , de sauter une ligne pour rendre l'aspect final plus lisible.

**Comment by WebDevJL** [comment]
@over-e 
Il faut utiliser des balises html simples comme pour l'exemple ci-dessous :
![translations](https://cloud.githubusercontent.com/assets/3506074/20709655/e94e483c-b636-11e6-8668-a76befd95887.png)
![e bike mont blanc tour du mont blanc 1](https://cloud.githubusercontent.com/assets/3506074/20709659/ec9fff80-b636-11e6-9fc1-80802a4a54a7.png)

On peut faire beaucoup mieux mais le prix n'est pas le même...
Pour te former à l'HTML, il va falloir réfléchir comme on procède.

**Comment by WebDevJL** [comment]
@over-e : je te conseille de documenter l'usage des traductions si tu as le temps dans le guide utilisateur: https://docs.google.com/document/d/1yVQG594djXwh_hAsPQjSkJ_vTB2vNU9Xe4sxaeAtreA
