### ISSUE TITLE
Terms : Affichage du terms-legal-title

### ISSUE THREAD

**Issue by over-e** [Puzzlout/TrekToursFlyer#246]
Lorsque l'on clik sur {{footer_a_legal_terms_text}}, on affiche terms-legal-paragraph mais il faudrait aussi afficher terms-legal-title

**Comment by WebDevJL** [comment]
La solution serait de faire commen ce site: http://papermashup.com/simple-css-navigation/

Le menu n'apparait pas tout le temps mais en scrollant vers le haut, il réapparait.

**Comment by over-e** [comment]
Tu peux passer me voir avant de partir en we

**Comment by WebDevJL** [comment]
@over-e comme vu ensemble, on met ce bug de côté.
