### ISSUE TITLE
Cookies : : lien vers page "terms" impossible

### ISSUE THREAD

**Issue by over-e** [Puzzlout/TrekToursFlyer#251]
Lorsque la fenêtre d'acceptation des cookies apparait (sur smarthphone) le lien " click here"  ne va pas sur la page "terms" 

Sur PC et tablette : non testé

**Comment by WebDevJL** [comment]
@over-e test réalisé sur Samsung s4 et s2 avec Chrome et navigateur Android
respectivement sans répliqué le souci. J'ai testé toutes les langues. Le
lien est fonctionnel.
