### ISSUE TITLE
Diminuer la taille du bloc "cookie consent"

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#252]
@over-e J'ai mis le bloc d'information des cookies plus petit et discret. Qu'en dis-tu ?

Livré sur http://puzzlout.com/trektours/public/web

PS: efface tes cookies

**Comment by over-e** [comment]
C'est mieux 
Merci

**Comment by WebDevJL** [comment]
@over-e Version 1.0.6 livrée sur http://ebikemontblanc.com
