### ISSUE TITLE
Design général

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#255]
> Stéphane a dit :
> Peut-être une modification générale du style des polices et couleurs vertes des boutons etc… (selon le futur logo et charte)

**Comment by WebDevJL** [comment]
@over-e 

Il faudra définir plus précisement le besoin. Est-ce que :
- vous avez une idée claire en tête ?
- ou faut-il que je vous propose une solution ?

La réponse déterminera la direction à prendre.

**Comment by WebDevJL** [comment]
@over-e 

# Résumé sur ce point
## Client

N/A

## Prestations Puzzlout

- Puzzlout utilisera la même taille de police pour les textes de la page Produit que le paragraphe de la section "Description" de la page Accueil

# Questions
## Client

Aucune.

## Puzzlout

1. Il faudra définir plus précisement le besoin. Est-ce que :
  a. vous avez une idée claire en tête ?
  b. ou faut-il que je vous propose une solution ?

**Comment by over-e** [comment]
On proposera la police et la couleur dès que nous aurons le logo
