### ISSUE TITLE
Modifications Header

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#256]
> Stéphane a dit :
> - Logo : rajouer un logo sur le Header et le faire apparaitre sur les Onlget des navigateurs
> - Rajouter « reserver » après     Home – autour du Mt Bl – contact/tel – réserver 
> - Voir comment on peut mettre Contact et le N° téléphone

**Comment by WebDevJL** [comment]
> - Logo : rajouer un logo sur le Header et le faire apparaitre sur les Onlget des navigateurs

1. il faut un logo pour le Header. Pour la taille, ça dépend du logo mais idéalement, il faudrait quelque chose de max. 28px de haut. A voir ce que tu fourniras.
2. il faut un “favicon” de 16x16 pixels pour l’onglet navigateur

> - Rajouter « reserver » après     Home – autour du Mt Bl – contact/tel – réserver 

1. Ok. Il faudra fournir le lien externe. 
2. Doit-il être paramétrable ?

> - Voir comment on peut mettre Contact et le N° téléphone

Ok, point de design UI

**Comment by over-e** [comment]
_Logo : rajouer un logo sur le Header et le faire apparaitre sur les Onlget des navigateurs_

    il faut un logo pour le Header. Pour la taille, ça dépend du logo mais idéalement, il faudrait quelque chose de max. 28px de haut. A voir ce que tu fourniras.
    il faut un “favicon” de 16x16 pixels pour l’onglet navigateur

        _Rajouter « reserver » après Home – autour du Mt Bl – contact/tel – réserver_

    Ok. Il faudra fournir le lien externe.
    Doit-il être paramétrable ?
Stéphane 14-02-2017: oui il faut le rendre paramétrable

        _Voir comment on peut mettre Contact et le N° téléphone_

Ok, point de design UI

**Comment by WebDevJL** [comment]
@over-e 

# Résumé sur ce point
## Client
Le client fournit :
- un logo pour le Header. Pour la taille, ça dépend du logo mais idéalement, il faudrait quelque chose de max. 28px de haut
- un “favicon” de 16x16 pixels pour l’onglet navigateur
- un lien externe pour ajouter le lien "Réservation"

## Prestations Puzzlout

- Puzzlout propose un design amélioré du menu "Contact" pour inclure le numéro de téléphone.
- Puzzlout intègre le logo dans l'entête
- Puzzlout permet la modification du logo dans l'entête via le site d'admin
- Puzzlout ajoute le favicon au site
- Puzzlout permet la modification du favicon via le site d'admin
- Puzzlout permet la modification du lien "Réservation" via le site d'admin

# Questions
## Client

Aucune.

## Puzzlout

Aucune.

**Comment by WebDevJL** [comment]
@over-e j'ai mis à jour le résumé du point.

**Comment by over-e** [comment]
Pour le moment on ne chiffre pas les deux points suivants :

Puzzlout permet la modification du logo dans l'entête via le site d'admin
Puzzlout permet la modification du favicon via le site d'admin

**Comment by WebDevJL** [comment]
@over-e : merci de se rapporter [au Google Docs partagé](https://docs.google.com/document/d/160hUDFXS1mJeaQw8IzrLbpKx9lcGedWwogQ6y2WJehU/edit#heading=h.2few8y3yk5up) pour la prise en compte de ces remarques.
