### ISSUE TITLE
Accueil 

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#257]
> Stéphane a dit :
> - Bloc Description : changer la photo (rendre parametrable si possible), changer les tons de la photos 
> - Bloc Contact : mettre le lien vers « reservit » URL parametrable

**Comment by WebDevJL** [comment]
@over-e 

# Résumé sur ce point
## Client
Le client fournit :
- une nouvelle photo en JPEG Progressive.

## Prestations Puzzlout

- Puzzlout soumet au Client un design pour l'ajout du lien "Réservation"
- Puzzlout intègre la nouvelle photo.
- Puzzlout permet la modification de la photo de la section "Description" via le site d'admin.
- Puzzlout permet la modification du lien "Réservation" via le site d'admin.
- Puzzlout ajoute le lien "Réservation" dans le bloc "Contact".

# Questions
## Client

Aucune.

## Puzzlout

1. Que signifie "changer les tons ? [Réponse](https://github.com/Puzzlout/TrekToursFlyer/issues/257#issuecomment-281121399)

**Comment by over-e** [comment]
Le site et les photos du site sont sur des tons très "gris -vert pale" , il n'y a pas de couleur "vive".
Mais il s'agit d'une prestation hors périmètre site flyer. donc on ne chiffre pas ce point.
