### ISSUE TITLE
Page produit

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#258]
> Stéphane a dit :
> - Changer la photo principale
> - Bloc HighLight 
>   - Mettre des vélos de couleurs à la place des étoiles 
>   - Mettre la même taille police de caractères que « bloc description » - à discuter
>   - Design : à revoir – à discuter
> - Bloc Parcours 
>   - Design : se rapprocher du style « bloc description »  - à discuter
>   - Supprimer la durée , montée descente (à confirmer si on peut garder à vide ?) 
>   - Mettre les Vélo selon la couleur
>   - Rendre paramétrable la photo 
>   - Rajouter bouton vers réserver (URL paramétrable)
> - Faire un autre Bloc parcours (pour les partenaires)
>   - Rendre paramétrable la photo		
> - ***Attention*** : ne pas mettre les liens URL vers les partenaires (ils seront uniquement en Footer)
> - Supprimer Bloc « ce qui est inclus »
> - Bloc autres infos 
>   - Mettre la même taille police de caractères que « bloc description » - à discuter
>   - Design : se rapprocher du style « bloc description »  - à discuter

**Comment by over-e** [comment]
- •	Changer la photo principale
- •	Bloc HighLight 

garder les étoiles mais faire lien vers bloc parcours
Mettre la même taille police de caractères que « bloc description » - à discuter

- •	Bloc Parcours 

Supprimer la durée , montée descente (à confirmer si on peut garder à vide ?) l’idée serait de pouvoir rajouter un texte en police plus petite
Rendre paramétrable la photo
Rajouter bouton vers réserver (URL paramétrable)  (sur les descriptions tour : mettre un bouton "book now")
Faire un autre Bloc parcours (pour les partenaires) on met les photos à droite
Rendre paramétrable la photo
Attention : ne pas mettre les liens URL vers les partenaires (ils seront uniquement en Footer)

- •	Bloc autres infos 

Mettre la même taille police de caractères que « bloc description » - à discuter
il faut supprimer le bandeau noir "Les E-bike tours". L’idée est de faire comme "http://www.savoie-mont-blanc.com/" .
Pour "autres infos" et "ce qui est inclus" : supprimer l'ensemble des blocs (bandeau noir et bloc )
On conserve la FAQ mais on enlève le bandeau noir "Questions fréquentes"

**Comment by WebDevJL** [comment]
@over-e 

# Résumé sur ce point
## Client

- Le client fournit la nouvelle photo principale
- Le client fournit un schéma simplifié du design des sections "Parcours" pour confirmer son besoin
- Le client fournit un schéma simplifié du design des sections "Parcours pour partenaires" pour confirmer son besoin
- Le client accepte la nouvelle design des sections "Parcours"


## Prestations Puzzlout

- Puzzlout prend en compte la modification de la taille de la police de caractère dans #255 
- Puzzlout met à jour la photo principale
- Puzzlout ajoute aux étoiles de la section "Highlights" un lien qui mène au parcours associé
- Puzzlout redesign les sections "Parcours" prenant exemple sur l'annexe 1. On alterne image / description de gauche à droite.
  - Puzzlout fournit un design des sections "Parcours" (hors section "Parcours pour partenaires") en reprenant le design de Savoie Mont blanc (voir annexe 1) : Un titre, un texte descriptif de petite taille et un lien (cf. point suivant pour le lien).
  - Puzzlout permet la modification de chaque image de section "Parcours" via le site d'admin.
  - Puzzlout ajoute un lien "Réservation" sur chaque section "Parcours". 
  - Puzzlout permet la modification du lien "Réservation" via le site d'admin.
  - Puzzlout fournit un design de la section "Parcours pour partenaires" à partir du besoin du Client
  - Puzzlout permet la modification de l'image de la section "Parcours pour partenaires" via le site d'admin
- Puzzlout supprime toutes les entêtes de section
- Puzzlout supprime les sections "Autres Infos" et "Ce qui est inclus". 

# Questions
## Client

Aucune.

## Puzzlout

1. Peut-on clarifier [ce commentaire](https://github.com/Puzzlout/TrekToursFlyer/issues/258#issuecomment-281635799) ?
 
# Annexes
## Annexe 1
![savoie-mont-blanc-design](https://cloud.githubusercontent.com/assets/3506074/23198913/fb48d116-f8ca-11e6-88ed-6957269aa871.png)

**Comment by over-e** [comment]
Lorsque l'on passe en mode Smarthphone , lorsque l'on scrolle, il faudra faire attention que le passage de "parcours" vers "partenaire" se fasse avec deux photos de suite et pas deux texte de suite (car pour l'un les photos sont à droite et l'autre à gauche)

**Comment by WebDevJL** [comment]
> @over-e a dit :
> Lorsque l'on passe en mode Smarthphone , lorsque l'on scrolle, il faudra faire attention que le passage de "parcours" vers "partenaire" se fasse avec deux photos de suite et pas deux texte de suite (car pour l'un les photos sont à droite et l'autre à gauche)

à clarifier demain
