### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#259]
> Stéphane a dit :
> - Lien partenaires prévoir 6 partenaires et rendre logo et URL paramétrable

**Comment by over-e** [comment]
Mettre aussi un lien FaceBook et twitter

**Comment by WebDevJL** [comment]
@over-e 

# Résumé sur ce point
## Client

N/A

## Prestations Puzzlout

- Puzzlout propose un nouveau design du footer avec les 6 liens
- Puzzlout a déjà implémente les liens sociaux : Facebook, Twitter, Google +  et Pinterest si leur lien respectif est fourni.

# Questions
## Client

Aucune.

## Puzzlout

1. Un lien étant composé d'une URL, d'un texte et d'une image "logo", affichons-nous seulement les liens si les premières valeurs sont fournies ?

**Comment by over-e** [comment]
les liens sont composés de texte , image et URL : on peut ne mettre que le texte sans image ?
On ne peut mettre que image sans texte ?
je ne sais pas si on va mettre que des textes ou si on va mettre des images ?
A clarifier

**Comment by WebDevJL** [comment]
@over-e : On peut avoir des liens avec du texte, ou une image ou les deux. Cf. [Google Docs partagé](https://docs.google.com/document/d/160hUDFXS1mJeaQw8IzrLbpKx9lcGedWwogQ6y2WJehU/edit#heading=h.t1t7sswgwcx).
