### ISSUE TITLE
Create partial view for footer section

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#26]

**Comment by damirius** [comment]
@WebDevJL

I've removed footer from the layout and added it as a partial. Can you tell me exact links and if the "social" view should be included in footer as well? If it should, can you tell me where we should put it and which links does it contains?

**Comment by WebDevJL** [comment]
@damirius yes, it will be in the footer but maybe also in the header. For now, just add a Facebook link, a Twitter link and Instagram link (all the homepage for now). We will edit those links later via the admin site.
Do it under issue #27.

Thanks.
