### ISSUE TITLE
Create Home page Controller

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#3]
This is simply to setup the Home page controller with Symphony. 

The final content will be added in another task (issue to be created).

**Comment by gsouvik** [comment]
@WebDevJL 
I wanted to start with this. Just asking, I would have to create the controller file for the homepage, right? Should I use an empty template to display a message, you mentioned the final content will be another issue.

Also you mentioned "Your branch should be named after the milestone you work on". So should I create a branch "feature_homepage_controller" and push code through it? Sorry if I'm being repetitive, I'm sure this would ease up for me after I complete a full iteration of feature development.

Thank you.

**Comment by WebDevJL** [comment]
> I wanted to start with this. Just asking, I would have to create the controller file for the homepage, right? Should I use an empty template to display a message, you mentioned the final content will be another issue.

Yes

> Also you mentioned "Your branch should be named after the milestone you work on". So should I create a branch "feature_homepage_controller" and push code through it? Sorry if I'm being repetitive, I'm sure this would ease up for me after I complete a full iteration of feature development.

No, it would be feature_homepage or even f_homepage.

Thanks.

**Comment by gsouvik** [comment]
@WebDevJL 
Homepage controller created. Route is "/"
Previous "/" is now "/default"

Created relevant view files under proper directory structure. Please review and let me know.

**Comment by WebDevJL** [comment]
@gsouvik all good for now.
