### ISSUE TITLE
Add tooltips to the vertical menu

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#36]
We need to add to the vertical menu tooltips to help the customer understand the meaning of each icon.

Use the same solution as the FWM project but use Lexik bundle integrated by Damir (see #20).

Check if the JS library used for the tooltips is present in Bower packages list.

**Comment by damirius** [comment]
@WebDevJL 

Hey, just wanted to ask you about this. You mentioned some JS library we used before, but as far as I remember only Souvik worked on tooltips so I don't know exactly what we used. In any case, bootstrap comes with great tooltip feature you can check it out here http://www.w3schools.com/bootstrap/bootstrap_ref_js_tooltip.asp and here http://getbootstrap.com/javascript/#tooltips. It's really easy to implement, just need few attributes added to the element and we can use it to display the tooltip on 4 sides of that element https://drive.google.com/file/d/0B7Laiv0PjSvDLU5PUWVfNmNpQW8/view. For example on our vertical menu we can show them on the left side.
HTML will look something like this:

`<li><a data-toggle="tooltip" data-placement="left" title="{% trans from 'product' %}a_highlights_tooltip{% endtrans %}" href="#section-highlights"><span class="glyphicon glyphicon-alert"></span></a></li>`

**Comment by WebDevJL** [comment]
@damirius

You could search the FWM repo issues (closed) or the code base to find what
we used.

The main goal is to find something that:
- work well on desktop (using mouse hover) and smartphones (using single
  tap)
- easy to configure (left, right, top, bottom)
- can work with our translation system.

I will let you investigate.

Thanks

## 

Jérémie Litzer
Puzzlout

**Comment by damirius** [comment]
@WebDevJL 

This plugin hits all our goals.
It works on desktop like you saw in previous video, and here it is on smartphone https://drive.google.com/file/d/0B7Laiv0PjSvDa21ycFhJVlVuTnc/view, it triggers on click
We can set `data-placement` to left, right, bottom, top or mix it with auto, like `auto right` which will try to set it to right and if there is no space for tooltip it will return to default position.
It works with translations, we just need to add `trans` tag in the title attribute

**Comment by damirius** [comment]
@WebDevJL 

On sprint branch

**Comment by WebDevJL** [comment]
@damirius You work too fast ;) Thanks!

## 

Jérémie Litzer
Puzzlout
