### ISSUE TITLE
Create Product page controller

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#4]
Create the product page controller.

It needs to support several different products with a URL like: http://domain.com/product/1 or http://domain.com/product?id=1

Let me know which URL format is possible or suggest a better option.

**Comment by damirius** [comment]
@WebDevJL 
URLs should look like http://domain.com/product/1, when writing annotation `@Route("/product/{id}",requirements={"id"="\d+"},name="product_get")`
In any case, when do you want us to move onto separate branches?
I have this done, it's really 15 min task. We of course need to create entities for product if we want to have some real logic behind this controller action.

**Comment by WebDevJL** [comment]
@damirius 

For now, you push to master since I have prepared the guidelines to use branches.

However, make sure you unit test each new bundle, even if it is really simple. All cases must be tested. Once I add Travis CI and the other tools to the project, we will know what is missing. Coming soon!

**Comment by damirius** [comment]
@WebDevJL 

Not a problem. I've added few tests to our webtest case for product controller, it really doesn't show anything yet, but I made few asserts just to check it out.
It's on master branch.
Tell me if you want to leave this one open so we can continue to work with product entities and other stuff or if we want to continue our work on this one after we integrate it.

**Comment by WebDevJL** [comment]
@damirius : can you try to solve as many code style issues as you can from this report: https://www.codacy.com/app/webdev-jl/TrekToursFlyer/issues?&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlIFN0eWxlIl19XQ==

Thanks.

**Comment by WebDevJL** [comment]
@damirius 

An additional note: if there are files that are not our making but vendors, do not spent too long fixing them. We may just exclude them from the analysis.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I don't think it's smart to change any vendor files. Best thing to do is to only include src/ and test/ directories since we will change just that, everything else are configs and Symfony or 3rd party files.

**Comment by WebDevJL** [comment]
@damirius that's good! Thanks. 

I will add the var folder into the exclusion list.
