### ISSUE TITLE
Create a partial view to load carousel of two item

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#45]
@gsouvik This will be for displaying 2 treks that the client wants to advertise to promote the business.

In the flyer specifications doc, you have the example bootstrap carousel in full screen mode. Please something as close as possible to that.

Each item of the carousel will made of:
- an image
- an line of text centered
- a button to load the trek product page.

Styling will be part of another issue. This issue is for the HTML skeleton.

Ask your questions if you have any.

**Comment by gsouvik** [comment]
@WebDevJL 
I assume I am free to use couple of random photos from your email with subject "TREK : photos". Also I'm keeping the images in the path `Resources/images/`.

**Comment by gsouvik** [comment]
@WebDevJL 
Bootstrap carousel added on homepage. Currently I've kept the height to a fixed value of 600px. I'll revisit the style options as a part of the other issue you mentioned in the main issue description.

**Comment by WebDevJL** [comment]
@gsouvik can you remove the "Welcome to Homepage" message. We will not need it.

Thanks.

**Comment by WebDevJL** [comment]
@gsouvik I did this simple plus added a few things. I wanted to showcase it today. You can focus on your other tasks.
