### ISSUE TITLE
Create the customer requests page

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#71]
The task includes:
- the controller
- the actions
  - the index action to load the empty skeleton. it will load the list of requests
  - the update action to update a request to a certain status (to be confirmed). Action will be empty to start with.
- the views
  - index view: empty skeleton for now

It will call the "customer/getRequests" service from the API.

**Comment by damirius** [comment]
@WebDevJL 

I've created new page on `/admin/customerinforequests` route. There's filter form and table overview of all CRIs, in status cell admin can patch the status to RTC/RQC if needed.
