### ISSUE TITLE
bower.json deleted during a PR?

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursFlyer#76]

**Comment by WebDevJL** [comment]
@damirius @gsouvik 

Something weird happened: the bower.json file disappeared so I added it back. Please synchronize your local repo.
Let me know if you can run the application as well because I was having an error to get the bootstrap.min.css.

Thanks.

**Comment by gsouvik** [comment]
@WebDevJL I haven't committed any code recently, I last pulled yesterday evening and everything was working fine for me till then, I'll test again now and let you know if I see anything.

**Comment by WebDevJL** [comment]
@gsouvik don't worry. It was maybe a miss from me. You can continue your work :)

**Comment by damirius** [comment]
@WebDevJL 

Everything was already there fixed when you merged it today with feature_appoptimisations because I setup layout stylesheets/javascripts again. Just added back bowerrc

**Comment by damirius** [comment]
@WebDevJL 

Everything should be fixed and merged

**Comment by WebDevJL** [comment]
@damirius Thanks.
